apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hybridnet-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: hybridnet-daemon
  template:
    metadata:
      labels:
        app: hybridnet-daemon
    spec:
      tolerations:
        - operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      priorityClassName: system-cluster-critical
      serviceAccountName: hybridnet
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: install-cni
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: {{ .Values.images.hybridnet.imagePullPolicy }}
          command: ["/hybridnet/install-cni.sh"]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - mountPath: /etc/cni/net.d
              name: cni-conf
            - mountPath: /opt/cni/bin
              name: cni-bin
            - mountPath: /hybridnet/00-hybridnet.conflist
              name: cni-conf-source
              subPath: cni-config
          env:
            - name: NEEDED_COMMUNITY_CNI_PLUGINS
              value: {{ .Values.daemon.neededCommunityCNIPlugins }}
      containers:
        - name: cni-daemon
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: {{ .Values.images.hybridnet.imagePullPolicy }}
          command:
            - sh
            - /hybridnet/start-daemon.sh
          args:
            {{ if (ne .Values.daemon.preferVxlanInterfaces "") }}
            - --prefer-vxlan-interfaces={{ .Values.daemon.preferVxlanInterfaces }}
            {{ end }}
            {{ if ne .Values.daemon.preferVlanInterfaces "" }}
            - --prefer-vlan-interfaces={{ .Values.daemon.preferVlanInterfaces }}
            {{ end }}
            {{ if ne .Values.daemon.preferBGPInterfaces "" }}
            - --prefer-bgp-interfaces={{ .Values.daemon.preferBGPInterfaces }}
            {{ end }}
            {{ if ne .Values.daemon.vtepAddressCIDRs "" }}
            - --vtep-address-cidrs={{ .Values.daemon.vtepAddressCIDRs }}
            {{ end }}
            - --patch-calico-pod-ips-annotation={{ .Values.daemon.enableNetworkPolicy }}
            - --check-pod-connectivity-from-host={{ .Values.daemon.checkPodConnectivityFromHost }}
            - --enable-vlan-arp-enhancement={{ .Values.daemon.enableVlanARPEnhancement }}
            - --feature-gates=MultiCluster={{ .Values.multiCluster }}
          securityContext:
            runAsUser: 0
            privileged: true
          {{- if .Values.daemon.resources }}
          resources:
            {{- toYaml .Values.daemon.resources | trim | nindent 12 }}
          {{- end }}
          env:
            - name: DEFAULT_IP_FAMILY
              value: {{ .Values.defaultIPFamily }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- if .Values.daemon.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.daemon.livenessProbe | trim | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /run/cni
              name: host-run-cni
            - mountPath: /lib/modules
              name: host-modules
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /var/run/
              name: host-var-run
              mountPropagation: Bidirectional
        {{ if .Values.daemon.enableNetworkPolicy }}
        - name: felix
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          imagePullPolicy: {{ .Values.images.hybridnet.imagePullPolicy }}
          command:
            - /hybridnet/policyinit.sh
          args:
            - calico-felix
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: FELIX_TYPHAADDR
              value: "localhost:{{ .Values.daemon.typha.serverPort }}"
          {{- if and .Values.daemon.felix .Values.daemon.felix.resources }}
          resources:
            {{- toYaml .Values.daemon.felix.resources | trim | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
            runAsUser: 0
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
              host: localhost
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
              host: localhost
            periodSeconds: 10
        - name: typha
          image: "{{ .Values.images.registryURL }}/{{ .Values.images.hybridnet.image }}:{{ .Values.images.hybridnet.tag }}"
          command:
            - /hybridnet/policyinit.sh
          args:
            - calico-typha
          ports:
            - containerPort: {{ .Values.daemon.typha.serverPort }}
              name: calico-typha
              protocol: TCP
          env:
            # Enable "info" logging by default.  Can be set to "debug" to increase verbosity.
            - name: TYPHA_LOGSEVERITYSCREEN
              value: "info"
            # Disable logging to file and syslog since those don't make sense in Kubernetes.
            - name: TYPHA_LOGFILEPATH
              value: "none"
            - name: TYPHA_LOGSEVERITYSYS
              value: "none"
            # Monitor the Kubernetes API to find the number of running instances and rebalance
            # connections.
            - name: TYPHA_CONNECTIONREBALANCINGMODE
              value: "kubernetes"
            - name: TYPHA_DATASTORETYPE
              value: "kubernetes"
            - name: TYPHA_HEALTHENABLED
              value: "true"
            - name: TYPHA_MAXCONNECTIONSLOWERLIMIT
              value: "1"
            # Uncomment these lines to enable prometheus metrics.  Since Typha is host-networked,
            # this opens a port on the host, which may need to be secured.
            #- name: TYPHA_PROMETHEUSMETRICSENABLED
            #  value: "true"
            #- name: TYPHA_PROMETHEUSMETRICSPORT
            #  value: "9093"
            - name: ServerPort
              value: "{{ .Values.daemon.typha.serverPort }}"
          {{- if and .Values.daemon.typha .Values.daemon.typha.resources }}
          resources:
            {{- toYaml .Values.daemon.typha.resources | trim | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9098
              host: localhost
            periodSeconds: 30
            initialDelaySeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9098
              host: localhost
            periodSeconds: 10
        {{ end }}
      nodeSelector:
        kubernetes.io/os: "linux"
      volumes:
        - name: host-modules
          hostPath:
            path: /lib/modules
        - name: host-run-cni
          hostPath:
            path: /run/cni
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        - name: cni-conf-source
          configMap:
            name: hybridnet-cni-conf
            items:
              - key: cni-config
                path: cni-config
        - name: host-var-run
          hostPath:
            path: /var/run/
            type: "Directory"

