images:
  hybridnet:
    image: hybridnetdev/hybridnet
    tag: v0.4.2
  registryURL: "docker.io"

# -- It's always encouraged to use an overlay network to finish some general jobs in hybridnet. This
# chart will always create an "init" overlay Network/Subnet to initialize the K8s cluster. "init" Network/Subnet
# will only be created once.
init:
  # -- CIDR of "init" Subnet.
  cidr: 100.64.0.0/16

  # -- IP version of the init subnet. "4" for ipv4, "6" for ipv6
  ipVersion: "4"

  # -- VNI of the default overlay vxlan Network.
  vxlanID: 4

manager:
  # -- The number of manager pods
  replicas: 3

webhook:
  # -- Only the pods match the additionalPodMatchExpressions will be validate by hybridnet webhook.
  additionalPodMatchExpressions:
    - key: app
      operator: NotIn
      values: [ "kube-proxy" ]

  # -- The number of webhook pods
  replicas: 3

daemon:
  # -- Whether enable the NetworkPolicy functions of hybridnet.
  enableNetworkPolicy: true

  # -- The physical interfaces on each node to transmit vlan/vxlan/bgp packets, which should be confirmed
  # before network config is actually applied, or you might have to face the risk of rebooting the machine.
  #
  ## Each one of them is an interface name string list, using commons as separator. Daemon will always use
  ## the first available interface name in each list. If empty, daemon will choose interface by default route.
  preferVxlanInterfaces: ""
  preferVlanInterfaces: ""
  preferBGPInterfaces: ""

# -- Whether pod IP of stateful workloads will be retained by default. true or false
## Ref: https://github.com/alibaba/hybridnet/wiki/Static-pod-ip-addresses-for-StatefulSet
defualtIPRetain: true

# -- The default value when pod's network type is unspecified. Overlay or Underlay
## Ref: https://github.com/alibaba/hybridnet/wiki/Change-default-network-type
defualtNetworkType: Overlay

# -- Enable the MultiCluster feature. true or false
multiCluster: false

# -- Enable the DualStack feature. IPv6 is disabled when is dualStack is not enable. true or false
dualStack: false
